# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "keks1@keks.net",
  "avatarPath": "keks.png",
  "name": "Keks1",
  "password": "123456"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@keks.net",
  "password": "123456"
}

###

## Проверка авторизации

GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3NAa2Vrcy5uZXQiLCJuYW1lIjoiS2VrcyIsImlkIjoiNjcxM2JmZGRiZTdiMTZjNDg5NTE2MTkwIiwiaWF0IjoxNzMwNTUwOTA3LCJleHAiOjE3MzA3MjM3MDd9.5lHV8891a-lSsDnFQgxi_YB2DgpAmrG2x6TVXuYdLdw

###
